# Generated by Django 5.2.4 on 2025-08-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('hero', models.CharField(max_length=200, verbose_name='Главный герой')),
                ('goal', models.TextField(verbose_name='Цель квеста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_data', models.JSONField(verbose_name='Данные квеста в JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='quest_app.questinput')),
            ],
        ),
    ]
