# Generated by Django 5.2.4 on 2025-08-01 19:41

import quest_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_data',
            field=quest_app.fields.UnicodeJSONField(verbose_name='Данные квеста в JSON'),
        ),
    ]
